from fastapi import FastAPI
from pydantic import BaseModel

#Objeto
app = FastAPI()

class Tracks(BaseModel):
    Id: int
    Artista: str
    Cancion: str
    Genero: str

tracks = [
Tracks(Id=0, Artista="nirvana", Cancion="breed", Genero="grunge"),
Tracks(Id=1, Artista="lisa", Cancion="guren", Genero="rock"),
Tracks(Id=2, Artista="the cure", Cancion="just like heaven", Genero="rock"),
Tracks(Id=3, Artista="nirvana", Cancion="smell like teen spirit", Genero="grunge"),
Tracks(Id=4, Artista="the cure", Cancion="a night like this", Genero="rock"),
Tracks(Id=5, Artista="the pixies", Cancion="bone machine", Genero="rock"),
Tracks(Id=6, Artista="the pixies", Cancion="gigantic", Genero="rock"),
Tracks(Id=7, Artista="the pixies", Cancion="head on", Genero="rock"),
Tracks(Id=8, Artista="the pixies", Cancion="hey", Genero="rock"),
Tracks(Id=9, Artista="the pixies", Cancion="where is my mind?", Genero="rock"),
Tracks(Id=10, Artista="the pixies", Cancion="cactus", Genero="rock"),
Tracks(Id=11, Artista="venom", Cancion="burn in hell", Genero="metal"),
Tracks(Id=12, Artista="venom", Cancion="house of pain", Genero="metal"),
Tracks(Id=13, Artista="venom", Cancion="warhead", Genero="metal"),
Tracks(Id=14, Artista="slipknot", Cancion="before i forget", Genero="nu-metal"),
Tracks(Id=15, Artista="slipknot", Cancion="duality", Genero="nu-metal"),
Tracks(Id=16, Artista="slipknot", Cancion="duality", Genero="nu-metal"),
Tracks(Id=17, Artista="slipknot", Cancion="killpop", Genero="nu-metal"),
Tracks(Id=18, Artista="slipknot", Cancion="lech", Genero="nu-metal"),
Tracks(Id=19, Artista="slipknot", Cancion="psychosocial", Genero="nu-metal"),
Tracks(Id=20, Artista="slipknot", Cancion="sulfur", Genero="nu-metal"),
Tracks(Id=21, Artista="slipknot", Cancion="vendetta", Genero="nu-metal"),
Tracks(Id=22, Artista="slipknot", Cancion="custer", Genero="nu-metal"),
Tracks(Id=23, Artista="slipknot", Cancion="dead memories", Genero="nu-metal"),
Tracks(Id=24, Artista="system of a down", Cancion="aerials", Genero="nu-metal"),
Tracks(Id=25, Artista="system of a down", Cancion="lonely day", Genero="nu-metal"),
Tracks(Id=26, Artista="system of a down", Cancion="psycho", Genero="nu-metal"),
Tracks(Id=27, Artista="system of a down", Cancion="revenga", Genero="nu-metal"),
Tracks(Id=28, Artista="system of a down", Cancion="sad statue", Genero="nu-metal"),
Tracks(Id=29, Artista="system of a down", Cancion="roulette", Genero="nu-metal"),
Tracks(Id=30, Artista="system of a down", Cancion="toxicity", Genero="nu-metal"),
Tracks(Id=31, Artista="green day", Cancion="american idiot", Genero="punk-rock"),
Tracks(Id=32, Artista="green day", Cancion="basket case", Genero="punk-rock"),
Tracks(Id=33, Artista="green day", Cancion="boulevard of the broken dreams", Genero="punk-rock"),
Tracks(Id=34, Artista="green day", Cancion="chump", Genero="punk-rock"),
Tracks(Id=35, Artista="green day", Cancion="21 guns", Genero="punk-rock"),
Tracks(Id=36, Artista="green day", Cancion="holiday", Genero="punk-rock"),
Tracks(Id=37, Artista="green day", Cancion="lady cobra", Genero="punk-rock"),
Tracks(Id=38, Artista="green day", Cancion="oh love", Genero="punk-rock"),
Tracks(Id=39, Artista="green day", Cancion="she", Genero="punk-rock"),
Tracks(Id=40, Artista="green day", Cancion="whatsername", Genero="punk-rock"),
Tracks(Id=41, Artista="green day", Cancion="longview", Genero="punk-rock"),
Tracks(Id=42, Artista="green day", Cancion="wake me up when september ends", Genero="punk-rock"),
Tracks(Id=43, Artista="green day", Cancion="when i come around", Genero="punk-rock"),
Tracks(Id=44, Artista="the ramones", Cancion="i love you", Genero="punk-rock"),
Tracks(Id=45, Artista="the ramones", Cancion="blitzkrieg bop", Genero="punk-rock"),
Tracks(Id=46, Artista="the ramones", Cancion="i wanna be sedated", Genero="punk-rock"),
Tracks(Id=47, Artista="nirvana", Cancion="in bloom", Genero="grunge"),
Tracks(Id=48, Artista="nirvana", Cancion="scoff", Genero="grunge"),
Tracks(Id=49, Artista="nirvana", Cancion="love buzz", Genero="grunge"),
Tracks(Id=50, Artista="alice in chains", Cancion="man in the box", Genero="grunge"),
Tracks(Id=51, Artista="alice in chains", Cancion="them bones", Genero="grunge"),
Tracks(Id=52, Artista="alice in chains", Cancion="would?", Genero="grunge"),
Tracks(Id=53, Artista="alice in chains", Cancion="got me wrong", Genero="grunge"),
Tracks(Id=54, Artista="iron maiden", Cancion="aces high", Genero="heavy metal"),
Tracks(Id=55, Artista="iron maiden", Cancion="dance of death", Genero="heavy metal"),
Tracks(Id=56, Artista="iron maiden", Cancion="fear of the dark", Genero="heavy metal"),
Tracks(Id=57, Artista="iron maiden", Cancion="phantom of the opera", Genero="heavy metal"),
Tracks(Id=58, Artista="iron maiden", Cancion="run to the hills", Genero="heavy metal"),
Tracks(Id=59, Artista="iron maiden", Cancion="the number of the beast", Genero="heavy metal"),
Tracks(Id=60, Artista="iron maiden", Cancion="the trooper", Genero="heavy metal"),
Tracks(Id=61, Artista="iron maiden", Cancion="the wicker man", Genero="heavy metal"),
Tracks(Id=62, Artista="iron maiden", Cancion="wasted years", Genero="heavy metal"),
Tracks(Id=63, Artista="iron maiden", Cancion="2 minutes to midnight", Genero="heavy metal"),
Tracks(Id=64, Artista="black sabbath", Cancion="paranoid", Genero="heavy metal"),
Tracks(Id=65, Artista="black sabbath", Cancion="iron man", Genero="heavy metal"),
Tracks(Id=66, Artista="black sabbath", Cancion="lady evil", Genero="heavy metal"),
Tracks(Id=67, Artista="black sabbath", Cancion="N.I.B", Genero="heavy metal"),
Tracks(Id=68, Artista="black sabbath", Cancion="electric funeral", Genero="heavy metal"),
Tracks(Id=69, Artista="black sabbath", Cancion="rat salad", Genero="heavy metal"),
Tracks(Id=70, Artista="black sabbath", Cancion="war pig", Genero="heavy metal"),
Tracks(Id=71, Artista="black sabbath", Cancion="crazy train", Genero="heavy metal"),
Tracks(Id=72, Artista="blink 182", Cancion="always", Genero="punk-rock"),
Tracks(Id=73, Artista="blink 182", Cancion="adam's song", Genero="punk-rock"),
Tracks(Id=74, Artista="blink 182", Cancion="feeling this", Genero="punk-rock"),
Tracks(Id=75, Artista="blink 182", Cancion="all of this", Genero="punk-rock"),
Tracks(Id=76, Artista="blink 182", Cancion="asthenia", Genero="punk-rock"),
Tracks(Id=77, Artista="blink 182", Cancion="carousel", Genero="punk-rock"),
Tracks(Id=78, Artista="blink 182", Cancion="down", Genero="punk-rock"),
Tracks(Id=79, Artista="blink 182", Cancion="easy target", Genero="punk-rock"),
Tracks(Id=80, Artista="blink 182", Cancion="first date", Genero="punk-rock"),
Tracks(Id=81, Artista="blink 182", Cancion="go", Genero="punk-rock"),
Tracks(Id=82, Artista="blink 182", Cancion="here's tou letter", Genero="punk-rock"),
Tracks(Id=83, Artista="blink 182", Cancion="i miss you", Genero="punk-rock"),
Tracks(Id=84, Artista="blink 182", Cancion="i'm lost without you", Genero="punk-rock"),
Tracks(Id=85, Artista="blink 182", Cancion="obvious", Genero="punk-rock"),
Tracks(Id=86, Artista="blink 182", Cancion="stockholm syndrome", Genero="punk-rock"),
Tracks(Id=87, Artista="blink 182", Cancion="violence", Genero="punk-rock"),
Tracks(Id=88, Artista="blink 182", Cancion="dammit", Genero="punk-rock"),
Tracks(Id=89, Artista="blink 182", Cancion="mutt", Genero="punk-rock"),
Tracks(Id=90, Artista="megadeth", Cancion="addicted to chaos", Genero="thrash metal"),
Tracks(Id=91, Artista="megadeth", Cancion="die dead enough", Genero="thrash metal"),
Tracks(Id=92, Artista="megadeth", Cancion="in my darkest hour", Genero="thrash metal"),
Tracks(Id=93, Artista="megadeth", Cancion="trust", Genero="thrash metal"),
Tracks(Id=94, Artista="metallica", Cancion="enter sandman", Genero="thrash metal"),
Tracks(Id=95, Artista="metallica", Cancion="master of puppets", Genero="thrash metal"),
Tracks(Id=96, Artista="metallica", Cancion="fuel", Genero="thrash metal"),
Tracks(Id=97, Artista="metallica", Cancion="my apocalypse", Genero="thrash metal"),
Tracks(Id=98, Artista="metallica", Cancion="nothing else matters", Genero="thrash metal"),
Tracks(Id=99, Artista="metallica", Cancion="one", Genero="thrash metal"),
Tracks(Id=100, Artista="metallica", Cancion="sad but true", Genero="thrash metal"),
Tracks(Id=101, Artista="metallica", Cancion="seek and destroy", Genero="thrash metal"),
Tracks(Id=102, Artista="metallica", Cancion="whiskey in the jar", Genero="thrash metal"),
Tracks(Id=103, Artista="metallica", Cancion="enter sandman", Genero="thrash metal"),
Tracks(Id=104, Artista="metallica", Cancion="one", Genero="thrash metal"),
Tracks(Id=105, Artista="metallica", Cancion="fuel", Genero="thrash metal"),
Tracks(Id=106, Artista="metallica", Cancion="battery", Genero="thrash metal"),
Tracks(Id=107, Artista="metallica", Cancion="the day that never comes ", Genero="thrash metal"),
Tracks(Id=108, Artista="nirvana", Cancion="dumb", Genero="grunge"),
Tracks(Id=109, Artista="nirvana", Cancion="all apologies", Genero="grunge"),
Tracks(Id=110, Artista="nirvana", Cancion="polly", Genero="grunge"),
Tracks(Id=111, Artista="nirvana", Cancion="very ape", Genero="grunge"),
Tracks(Id=112, Artista="nirvana", Cancion="oh, me", Genero="grunge"),
Tracks(Id=113, Artista="nirvana", Cancion="downer", Genero="grunge"),
Tracks(Id=114, Artista="nirvana", Cancion="sappy", Genero="grunge"),
Tracks(Id=115, Artista="nirvana", Cancion="stain", Genero="grunge"),
Tracks(Id=116, Artista="nirvana", Cancion="about a girl", Genero="grunge"),
Tracks(Id=117, Artista="nirvana", Cancion="milk it", Genero="grunge"),
Tracks(Id=118, Artista="nirvana", Cancion="school", Genero="grunge"),
Tracks(Id=119, Artista="nirvana", Cancion="dive", Genero="grunge"),
Tracks(Id=120, Artista="nirvana", Cancion="d-7", Genero="grunge"),
Tracks(Id=121, Artista="nirvana", Cancion="lithium", Genero="grunge"),
Tracks(Id=122, Artista="nirvana", Cancion="lounge act", Genero="grunge"),
Tracks(Id=122, Artista="nirvana", Cancion="blew", Genero="grunge"),
Tracks(Id=122, Artista="nirvana", Cancion="aero zeppelin", Genero="grunge"),
Tracks(Id=123, Artista="linkin park", Cancion="dont' stay", Genero="nu-metal"),
Tracks(Id=124, Artista="linkin park", Cancion="somewhere i belong", Genero="nu-metal"),
Tracks(Id=125, Artista="linkin park", Cancion="lying frim you", Genero="nu-metal"),
Tracks(Id=126, Artista="linkin park", Cancion="hit the floor", Genero="nu-metal"),
Tracks(Id=127, Artista="linkin park", Cancion="easier to run", Genero="nu-metal"),
Tracks(Id=128, Artista="linkin park", Cancion="faint", Genero="nu-metal"),
Tracks(Id=129, Artista="linkin park", Cancion="figure.09", Genero="nu-metal"),
Tracks(Id=130, Artista="linkin park", Cancion="breaking the habit", Genero="nu-metal"),
Tracks(Id=131, Artista="linkin park", Cancion="from the inside", Genero="nu-metal"),
Tracks(Id=132, Artista="linkin park", Cancion="nobody's listenig", Genero="nu-metal"),
Tracks(Id=133, Artista="linkin park", Cancion="numb", Genero="nu-metal"),
Tracks(Id=134, Artista="linkin park", Cancion="the catalyst", Genero="nu-metal"),
Tracks(Id=135, Artista="linkin park", Cancion="in the end", Genero="nu-metal"),
Tracks(Id=136, Artista="linkin park", Cancion="crawling", Genero="nu-metal"),
Tracks(Id=137, Artista="linkin park", Cancion="bleed it out", Genero="nu-metal"),
Tracks(Id=138, Artista="foo fighters", Cancion="everlong", Genero="rock"),
Tracks(Id=139, Artista="foo fighters", Cancion="the pretender", Genero="rock"),
Tracks(Id=140, Artista="foo fighters", Cancion="best of you", Genero="rock"),
Tracks(Id=141, Artista="foo fighters", Cancion="my hero", Genero="rock"),
Tracks(Id=142, Artista="foo fighters", Cancion="rope", Genero="rock"),
Tracks(Id=143, Artista="foo fighters", Cancion="these days", Genero="rock"),
Tracks(Id=144, Artista="foo fighters", Cancion="walk", Genero="rock"),
Tracks(Id=145, Artista="foo fighters", Cancion="run", Genero="rock"),
Tracks(Id=146, Artista="foo fighters", Cancion="let it die", Genero="rock"),
Tracks(Id=147, Artista="foo fighters", Cancion="come alive", Genero="rock"),
Tracks(Id=148, Artista="foo fighters", Cancion="long road to ruin", Genero="rock"),
Tracks(Id=149, Artista="foo fighters", Cancion="in your honor", Genero="rock"),
Tracks(Id=150, Artista="foo fighters", Cancion="no way back", Genero="rock"),
Tracks(Id=151, Artista="foo fighters", Cancion="the last song", Genero="rock"),
Tracks(Id=152, Artista="exwhyz", Cancion="d.y.d", Genero="j-pop"),
Tracks(Id=153, Artista="exwhyz", Cancion="stay with me", Genero="j-pop"),
Tracks(Id=154, Artista="exwhyz", Cancion="obsession", Genero="j-pop"),
Tracks(Id=155, Artista="exwhyz", Cancion="4:00 a.m", Genero="j-pop"),
Tracks(Id=156, Artista="exwhyz", Cancion="weekend", Genero="j-pop"),
Tracks(Id=157, Artista="exwhyz", Cancion="wanna dance", Genero="j-pop"),
Tracks(Id=158, Artista="exwhyz", Cancion="you and me", Genero="j-pop"),
Tracks(Id=159, Artista="exwhyz", Cancion="higher", Genero="j-pop"),
Tracks(Id=160, Artista="exwhyz", Cancion="universe", Genero="j-pop"),
Tracks(Id=161, Artista="exwhyz", Cancion="blaze", Genero="j-pop"),
Tracks(Id=162, Artista="exwhyz", Cancion="des speeching", Genero="j-pop"),
Tracks(Id=163, Artista="exwhyz", Cancion="answer", Genero="j-pop"),
Tracks(Id=164, Artista="exwhyz", Cancion="dive", Genero="j-pop"),
Tracks(Id=165, Artista="exwhyz", Cancion="lets's show", Genero="j-pop"),
Tracks(Id=166, Artista="exwhyz", Cancion="chase your back", Genero="j-pop"),
Tracks(Id=167, Artista="exwhyz", Cancion="iza!!", Genero="j-pop"),
Tracks(Id=168, Artista="exwhyz", Cancion="happy with you", Genero="j-pop"),
Tracks(Id=169, Artista="exwhyz", Cancion="error", Genero="j-pop"),
Tracks(Id=170, Artista="exwhyz", Cancion="haggling", Genero="j-pop"),
Tracks(Id=171, Artista="exwhyz", Cancion="hon-no", Genero="j-pop"),
Tracks(Id=172, Artista="exwhyz", Cancion="rather", Genero="j-pop"),
Tracks(Id=173, Artista="exwhyz", Cancion="have it my way", Genero="j-pop"),
Tracks(Id=174, Artista="exwhyz", Cancion="right now", Genero="j-pop"),
Tracks(Id=175, Artista="exwhyz", Cancion="tokyo moonlight", Genero="j-pop"),
Tracks(Id=176, Artista="fuzzy bumble", Cancion="any other way", Genero="rock inde"),
Tracks(Id=177, Artista="fuzzy bumble", Cancion="psychotic defect", Genero="rock inde"),
Tracks(Id=178, Artista="fuzzy bumble", Cancion="nadasé", Genero="rock inde"),
Tracks(Id=179, Artista="fuzzy bumble", Cancion="to kiss with concentration", Genero="rock inde"),
Tracks(Id=180, Artista="velvet revolver", Cancion="let it roll", Genero="hard rock"),
Tracks(Id=181, Artista="velvet revolver", Cancion="sucker train blues", Genero="hard rock"),
Tracks(Id=182, Artista="velvet revolver", Cancion="set me free", Genero="hard rock"),
Tracks(Id=183, Artista="velvet revolver", Cancion="slither", Genero="hard rock"),
Tracks(Id=184, Artista="depeche mode", Cancion="enjoy the silence", Genero="rock"),
Tracks(Id=185, Artista="depeche mode", Cancion="ghosts again", Genero="electronic rock"),
Tracks(Id=186, Artista="depeche mode", Cancion="wrong", Genero="electronic  rock"),
Tracks(Id=187, Artista="depeche mode", Cancion="precious", Genero="electronic rock"),
Tracks(Id=188, Artista="soundgarden", Cancion="black hole sun", Genero="grunge"),
Tracks(Id=189, Artista="audioslave", Cancion="like a stone", Genero="rock"),
Tracks(Id=190, Artista="audioslave", Cancion="be yourself", Genero="rock"),
Tracks(Id=191, Artista="audioslave", Cancion="i am the highway", Genero="rock"),
Tracks(Id=192, Artista="audioslave", Cancion="gasoline", Genero="rock"),
Tracks(Id=193, Artista="audioslave", Cancion="revelations", Genero="rock"),
Tracks(Id=194, Artista="audioslave", Cancion="light my way", Genero="rock"),
Tracks(Id=195, Artista="audioslave", Cancion="set it off", Genero="rock"),
Tracks(Id=195, Artista="audioslave", Cancion="what you are", Genero="rock"),
Tracks(Id=196, Artista="audioslave", Cancion="your time has coming", Genero="rock"),
Tracks(Id=197, Artista="audioslave", Cancion="the worm", Genero="rock"),
Tracks(Id=198, Artista="audioslave", Cancion="out of exile", Genero="rock"),
Tracks(Id=199, Artista="audioslave", Cancion="spoonman", Genero="rock"),
]

@app.get("/tracksclass/")
async def trackssclass():
    return (tracks)

@app.get("/tracksclass/{Id}")
async def tracksClass(Id:int):
    tracks_l = filter(lambda track: track.Id == Id, tracks)
    try:
        return list(tracks_l)[0] 
    except:
        return{"error": "track no encontrado"}

